# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-20 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userModel_app_1184099', '0002_auto_20210220_1146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
